### ISSUE TITLE
Document installation instructions and dependencies

### ISSUE THREAD

**Issue by malcomio** [Capgemini/drupalytics#5]
After enabling the module, going to http://drupal8.dev/code_analyzer causes this fatal error:

```
Fatal error: Class 'Gitonomy\Git\Admin' not found in /var/www/drupal8/modules/drupalytics/src/GitHandler.php on line 38
```

**Comment by legovaer** [comment]
That is because you will first need to install composer manager in order to get all the libraries. That's information that we'll need to add to the README :+1:

**Comment by legovaer** [comment]
This issue is resolved because the project has become a Drupal distribution (#14), so the user should not care about dependencies anymore. While installing the distribution, the installer will automatically download and install the required modules.
